server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: jaeger
          uri: https://github.com/anpeni/microserviciospostgre
          search-paths: config-data
  application:
    name: config-service
